cache:
  paths:
    - node_modules/

# VPS CONTABO 2
contabo2_deploy_test:
  stage: deploy
  environment: Dev
  script: "CONFIGURATION=dev docker compose -f docker-compose.deploy.yml -p swiss-knife_dev up -d --build"
  only:
    - contabo2_dev
  tags:
    - "vps-contabo2"

contabo2_deploy_prod:
  stage: deploy
  environment: Production
  script: "CONFIGURATION=production docker compose -f docker-compose.deploy.yml -p swiss-knife_production up -d --build"
  only:
    - contabo2_prod
  tags:
    - "vps-contabo2"
