version: '3'

services:
  angular:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION}
    container_name: swiss-knife_${CONFIGURATION}
    expose:
      - 5001
    image: dz/swiss-knife_${CONFIGURATION}
    restart: unless-stopped
