# NOTE: doesn't work at the moment!
version: '3.8'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - configuration=${CONFIGURATION}
    container_name: swiss-knife_${CONFIGURATION}
    expose:
      - 5001
    image: dz/swiss-knife_${CONFIGURATION}
    restart: unless-stopped
