version: '3.7'

services:
  react:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: swiss-knife_local
    env_file:
      - environments/web-dev.env
    image: dz/swiss-knife_local
    ports:
      - "3001:3000"
    stdin_open: true
    volumes:
      - .:/app
      - /app/node_modules
